// <auto-generated />
namespace ComesticOhui.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_company : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_company));
        
        string IMigrationMetadata.Id
        {
            get { return "201512211159167_add_company"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
